# Vocal learner, motor cortex
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m MoMaRaBaEnhancersNRSummit.txt -n 1 -o VocalLearnerMotorCortexBinaryPGLSOut/cortex_VocalLearner_results.csv -p RM-shared -q phyloglm -s 0 -t 4:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortexTrue.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortexTrue.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/cortex_VocalLearner_results_r1_s-1871314884.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m MoMaRaBaEnhancersNRSummit.txt -n 800 -o VocalLearnerMotorCortexBinaryPGLSOut/motorCortex_VocalLearner_round1.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex1.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex1.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound1Peaks.txt
grep -v -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound1Peaks.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results.csv | cut -f 1 -d , > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound1MissingPeaks.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound1MissingPeaks.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round1Missing.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m MoMaRaBaEnhancersNRSummit_round1Missing.txt -n 8 -o VocalLearnerMotorCortexBinaryPGLSOut/motorCortex_VocalLearner_round1a.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex1a.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex1a.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results_perm1k.csv
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results_perm1k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_peaks_perm1k_p005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_peaks_perm1k_p005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_preds_perm1k_p005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m cortex_VocalLearner_preds_perm1k_p005.txt -n 1000 -o VocalLearnerMotorCortexBinaryPGLSOut/motorCortex_VocalLearner_round2.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex2.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex2.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/*round2*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2Peaks.txt
sed '1d' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2Peaks.txt | sed 's/\"//g' > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2PeaksModified.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_preds_perm1k_p005.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2PeaksModified.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round2Missing.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m MoMaRaBaEnhancersNRSummit_round2Missing.txt -n 38 -o VocalLearnerMotorCortexBinaryPGLSOut/motorCortex_VocalLearner_round2a.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex2a.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex2a.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/*round2*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2AndaPeaks.txt
sed '1d' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2AndaPeaks.txt | sed 's/\"//g' > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2AndaPeaksModified.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_preds_perm1k_p005.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound2AndaPeaksModified.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round2AndaMissing.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/HumanOfRenamedAllNRSummit_cortexModified.bed --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round2AndaMissing.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/HumanOfRenamedAllNRSummit_cortexModified_vocalLearningRound2AndaMissing.bed
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MouseOfRenamedAllNRSummit_cortexModified.bed --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round2AndaMissing.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MouseOfRenamedAllNRSummit_cortexModified_vocalLearningRound2AndaMissing.bed
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results_perm10k.csv
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results_perm10k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_peaks_perm10k_p0005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_peaks_perm10k_p0005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_preds_perm10k_p0005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m cortex_VocalLearner_preds_perm10k_p0005.txt -n 370 -o VocalLearnerMotorCortexBinaryPGLSOut/motorCortex_VocalLearner_round3.csv -p RM-shared -q phyloglm -s 90000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex3.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex3.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/*round3*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound3Peaks.txt
sed '1d' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound3Peaks.txt | sed 's/\"//g' > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound3PeaksModified.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_preds_perm10k_p0005.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound3PeaksModified.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round3Missing.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/HumanOfRenamedAllNRSummit_cortexModified.bed --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round3Missing.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/HumanOfRenamedAllNRSummit_cortexModified_vocalLearningRound3Missing.bed
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MouseOfRenamedAllNRSummit_cortexModified.bed --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round3Missing.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MouseOfRenamedAllNRSummit_cortexModified_vocalLearningRound3Missing.bed
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results_perm100k.csv
awk -F , '$4 < 0.0005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results_perm100k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_peaks_perm100k_p00005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_peaks_perm100k_p00005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_preds_perm100k_p00005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m cortex_VocalLearner_preds_perm100k_p00005.txt -n 148 -o VocalLearnerMotorCortexBinaryPGLSOut/motorCortex_VocalLearner_round4.csv -p RM-shared -q phyloglm -s 900000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex4.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex4.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/*round4*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4Peaks.txt
sed '1d' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4Peaks.txt | sed 's/\"//g' > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4PeaksModified.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_preds_perm100k_p00005.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4PeaksModified.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round4Missing.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Boreoeutheria_VLtrait_modified.csv -b Vocal_Learner -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j M1VocalLearner -m MoMaRaBaEnhancersNRSummit_round4Missing.txt -n 139 -o VocalLearnerMotorCortexBinaryPGLSOut/motorCortex_VocalLearner_round4a.csv -p RM-shared -q phyloglm -s 400000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex4a.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSVocalLearnerMotorCortex4a.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/*round4a*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4aPeaks.txt
sed '1d' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4aPeaks.txt | sed 's/\"//g' > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4aPeaksModified.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round4Missing.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/vocalLearnerMotorCortexBinaryPGLSRound4aPeaksModified.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_round4aMissing.txt
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/VocalLearnerMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_VocalLearner_results_perm1m.csv

# Solitary, motor cortex
# No human orthologs of mouse peaks in WBS region
grep chr7 /ocean/projects/bio200034p/ikaplow/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5.bed | awk 'BEGIN{OFS="\t"} $2 < 74889376' |  awk 'BEGIN{OFS="\t"} $3 > 73228154 {print $1, $2, $3, $4"_ma", $5, $6, $7, $8, $9, $10}' > /ocean/projects/bio200034p/ikaplow/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed
grep chr7 /ocean/projects/bio200034p/ikaplow/RatAtac/M1/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_Homo_sapiens_summitExtendedMin50Max2XProtect5.bed | awk 'BEGIN{OFS="\t"} $2 < 74889376' |  awk 'BEGIN{OFS="\t"} $3 > 73228154 {print $1, $2, $3, $4"_ra", $5, $6, $7, $8, $9, $10}' > /ocean/projects/bio200034p/ikaplow/RatAtac/M1/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed
grep chr7 /ocean/projects/bio200034p/ikaplow/BatAtac/OfMBat1K/call-reproducibility_idr/execution/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_200MBat_SequenceNames_Homo_sapiens_summitExtendedMin50Max2XProtect5.bed | awk 'BEGIN{OFS="\t"} $2 < 74889376' |  awk 'BEGIN{OFS="\t"} $3 > 73228154 {print $1, $2, $3, $4"_ba", $5, $6, $7, $8, $9, $10}' > /ocean/projects/bio200034p/ikaplow/BatAtac/OfMBat1K/call-reproducibility_idr/execution/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_200MBat_SequenceNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed
cat /ocean/projects/bio200034p/ikaplow/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed /ocean/projects/bio200034p/ikaplow/RatAtac/M1/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed /ocean/projects/bio200034p/ikaplow/BatAtac/OfMBat1K/call-reproducibility_idr/execution/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_200MBat_SequenceNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed | cut -f4 > /ocean/projects/bio200034p/ikaplow/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS_andRat_andBat_peakNames.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak.inM1_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS_andRat_andBat_peakNames.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_WBS.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m MoMaRaBaEnhancersNRSummit_WBS.txt -n 1 -o SolitaryMotorCortexBinaryPGLSOut/cortex_solitary_results.csv -p RM-shared -q phyloglm -s 0 -t 2:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexBinaryPGLSOut/cortex_solitary_results_r1_s208682981.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m MoMaRaBaEnhancersNRSummit_WBS.txt -n 18 -o SolitaryMotorCortexBinaryPGLSOut/cortex_solitary_results_round1.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex1.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex1.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results_perm1k.csv
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results_perm1k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_peaks_perm1k_p005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_peaks_perm1k_p005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_preds_perm1k_p005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_solitary_preds_perm1k_p005.txt -n 1 -o SolitaryMotorCortexBinaryPGLSOut/cortex_solitary_results_round2.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex2.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results_perm10k.csv
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results_perm10k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_peaks_perm10k_p0005.txt # Same peak as for p < 0.05
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_solitary_preds_perm1k_p005.txt -n 1 -o SolitaryMotorCortexBinaryPGLSOut/cortex_solitary_results_round3.csv -p RM-shared -q phyloglm -s 90000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex3.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results_perm100k.csv
awk -F , '$4 < 0.0005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results_perm100k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_peaks_perm100k_p00005.txt # Same peak as for p < 0.05
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_solitary_preds_perm1k_p005.txt -n 1 -o SolitaryMotorCortexBinaryPGLSOut/cortex_solitary_results_round4.csv -p RM-shared -q phyloglm -s 900000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex4.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortex4.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_solitary_results_perm1m.csv

# Solitary, motor cortex, genome-wide
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m MoMaRaBaEnhancersNRSummit.txt -n 1 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results.csv -p RM-shared -q phyloglm -s 0 -t 2:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_r1_s1190878775.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m MoMaRaBaEnhancersNRSummit.txt -n 1000 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round1.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull1.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull1.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/*round1*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound1Peaks.txt
sed '1d' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound1Peaks.txt | sed 's/\"//g' > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound1PeaksModified.txt
python /jet/home/ikaplow/OCROrthologPrediction/src/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound1PeaksModified.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_solitaryRound1Missing.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m MoMaRaBaEnhancersNRSummit_solitaryRound1Missing.txt -n 1000 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round1a.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull1a.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull1a.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm1k.csv
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm1kPlus.csv
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm1k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm1k_p005.txt
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm1kPlus.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm1k_p005Plus.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm1k_p005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm1k_p005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm1k_p005Plus.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm1k_p005Plus.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_full_solitary_preds_perm1k_p005.txt -n 1000 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round2.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull2.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull2.bash
cat /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/*round2*csv | cut -f 1 -d , | uniq | sort | uniq > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound2Peaks.txt
sed '1d' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound2Peaks.txt | sed 's/\"//g' > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound2PeaksModified.txt
python /jet/home/ikaplow/OCROrthologPrediction/src/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm1k_p005Plus.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSRound2PeaksModified.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm1k_p005Plus_solitaryRound2Missing.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_full_solitary_preds_perm1k_p005Plus_solitaryRound2Missing.txt -n 397 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round2a.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull2a.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull2a.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm10k.csv
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm10kPlus.csv
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm10k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm10k_p0005.txt
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm10kPlus.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm10k_p0005Plus.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm10k_p0005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm10k_p0005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm10k_p0005Plus.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm10k_p0005Plus.txt
python /jet/home/ikaplow/OCROrthologPrediction/src/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm10k_p0005Plus.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm10k_p0005.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm10k_p0005Plus_solitaryRound3Missing.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_full_solitary_preds_perm10k_p0005.txt -n 378 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round3.csv -p RM-shared -q phyloglm -s 90000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull3.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull3.bash
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_full_solitary_preds_perm10k_p0005Plus_solitaryRound3Missing.txt -n 45 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round3a.csv -p RM-shared -q phyloglm -s 90000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull3a.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull3a.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm100k.csv
awk -F , '$4 < 0.0005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm100k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm100k_p00005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_peaks_perm100k_p00005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm100k_p00005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m cortex_full_solitary_preds_perm100k_p00005.txt -n 43 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round4.csv -p RM-shared -q phyloglm -s 900000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1999 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull4.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull4.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm1m.csv
python /jet/home/ikaplow/OCROrthologPrediction/src/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_preds_perm1k_p005Plus.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_solitaryRound2NotUsed.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j SolitaryM1 -m MoMaRaBaEnhancersNRSummit_solitaryRound2NotUsed.txt -n 1000 -o SolitaryMotorCortexFullBinaryPGLSOut/cortex_full_solitary_results_round2b.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull2b.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryMotorCortexFull2b.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/*round3* /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOutPlus
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/*round4* /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOutPlus
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_solitary_results_perm10kAll.csv

# Solitary, liver
# No human orthologs of mouse peaks in WBS region
grep chr7 /ocean/projects//bio200034p/ikaplow/MacaqueAtac/Liver/cromwell-executions/atac/1f5fd9f0-d389-4184-99cb-c1125fd7f064/call-reproducibility_idr/execution/LiftedPeaksFixed/optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5.bed | awk 'BEGIN{OFS="\t"} $2 < 74889376' |  awk 'BEGIN{OFS="\t"} $3 > 73228154 {print $1, $2, $3, $4"_ma", $5, $6, $7, $8, $9, $10}' > /ocean/projects//bio200034p/ikaplow/MacaqueAtac/Liver/cromwell-executions/atac/1f5fd9f0-d389-4184-99cb-c1125fd7f064/call-reproducibility_idr/execution/LiftedPeaksFixed/optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed
# No human orthologs of rat peaks in WBS region
grep chr7 /ocean/projects/bio200034p/ikaplow/CowDNase/Liver/atac/888ae501-7469-4afa-8890-e36f14f6c83b/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5.bed | awk 'BEGIN{OFS="\t"} $2 < 74889376' |  awk 'BEGIN{OFS="\t"} $3 > 73228154 {print $1, $2, $3, $4"_co", $5, $6, $7, $8, $9, $10}' > /ocean/projects/bio200034p/ikaplow/CowDNase/Liver/atac/888ae501-7469-4afa-8890-e36f14f6c83b/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed
grep chr7 /ocean/projects/bio200034p/ikaplow/PigDNase/Liver/atac/568838bc-4846-4491-8787-45b51e65bfee/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5.bed | awk 'BEGIN{OFS="\t"} $2 < 74889376' |  awk 'BEGIN{OFS="\t"} $3 > 73228154 {print $1, $2, $3, $4"_pi", $5, $6, $7, $8, $9, $10}' > /ocean/projects/bio200034p/ikaplow/PigDNase/Liver/atac/568838bc-4846-4491-8787-45b51e65bfee/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed
cat /ocean/projects//bio200034p/ikaplow/MacaqueAtac/Liver/cromwell-executions/atac/1f5fd9f0-d389-4184-99cb-c1125fd7f064/call-reproducibility_idr/execution/LiftedPeaksFixed/optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed /ocean/projects/bio200034p/ikaplow/CowDNase/Liver/atac/888ae501-7469-4afa-8890-e36f14f6c83b/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed /ocean/projects/bio200034p/ikaplow/PigDNase/Liver/atac/568838bc-4846-4491-8787-45b51e65bfee/peak/idr_reproducibility/LiftedPeaksFixed/idr.optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS.bed | cut -f4 > /ocean/projects/bio200034p/ikaplow/MacaqueAtac/Liver/cromwell-executions/atac/1f5fd9f0-d389-4184-99cb-c1125fd7f064/call-reproducibility_idr/execution/LiftedPeaksFixed/optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS_peakNames_andCow_andPig.txt
python /jet/home/ikaplow/RegElEvoCode/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoRaMaCoPiEnhancersNRSummit.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/MacaqueAtac/Liver/cromwell-executions/atac/1f5fd9f0-d389-4184-99cb-c1125fd7f064/call-reproducibility_idr/execution/LiftedPeaksFixed/optimal_peak_nonCDS_enhancerShort_GenBankNames_Homo_sapiens_summitExtendedMin50Max2XProtect5_WBS_peakNames_andCow_andPig.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoRaMaCoPiEnhancersNRSummit_WBS.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j Solitary -m MoRaMaCoPiEnhancersNRSummit_WBS.txt -n 1 -o SolitaryLiverBinaryPGLSOut/liver_solitary_results.csv -p RM-shared -q phyloglm -s 0 -t 2:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryLiver.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryLiver.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryLiverBinaryPGLSOut/liver_solitary_results_r1_s-1507051505.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j Solitary -m MoRaMaCoPiEnhancersNRSummit_WBS.txt -n 21 -o SolitaryLiverBinaryPGLSOut/liver_solitary_results_round1.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryLiver1.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryLiverBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_results_perm1k.csv
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_results_perm1k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_peaks_perm1k_p005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_peaks_perm1k_p005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoRaMaCoPiEnhancersNRSummit_WBS.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_preds_perm1k_p005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j Solitary -m liver_solitary_preds_perm1k_p005.txt -n 1 -o SolitaryLiverBinaryPGLSOut/liver_solitary_results_round2.csv -p RM-shared -q phyloglm -s 9000 -t 10:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryLiver2.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryLiver2.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryLiverBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_results_perm10k.csv
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_results_perm10k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_solitary_peaks_perm10k_p0005.txt # No peaks

# Solitary, PV, genome-wide, excluding 1st iteration for most peaks
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c PVSpeciesOrder.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j Solitary -m PV_MoHu_AvgActivityPredictions_boreoeutheria_222species_olapFilt_modified.txt -n 1 -o SolitaryPvBinaryPGLSOut/Pv_solitary_results.csv -p RM-shared -q phyloglm -s 0 -t 4:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryPv.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryPv.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryPvBinaryPGLSOut/Pv_solitary_results_r1_s-1676502495.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/Pv_solitary_results.csv
python /jet/home/ikaplow/OCROrthologPrediction/src/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/PV_MoHu_AvgActivityPredictions_boreoeutheria_222species_olapFilt_modified.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/Pv_solitary_peaks_perm1k_solitaryRound1Missing.txt --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/PV_MoHu_AvgActivityPredictions_boreoeutheria_222species_olapFilt_modified_solitaryRound1Missing.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c PVSpeciesOrder.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j Solitary -m PV_MoHu_AvgActivityPredictions_boreoeutheria_222species_olapFilt_modified_solitaryRound1Missing.txt -n 70 -o SolitaryPvBinaryPGLSOut/solitary_PV_round1a.csv -p RM-shared -q phyloglm -s 999 -t 5:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryPv1a.bash
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b solitary_living_euarchontoglires -c PVSpeciesOrder.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j Solitary -m PV_MoHu_AvgActivityPredictions_boreoeutheria_222species_olapFilt_modified.txt -n 1000 -o SolitaryPvBinaryPGLSOut/solitary_PV_round2.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryPv2.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSSolitaryPv2.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/Pv_solitary_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/SolitaryPvBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/Pv_solitary_results_perm10k.csv

# Group living, motor cortex
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m MoMaRaBaEnhancersNRSummit_WBS.txt -n 1 -o GroupLivingMotorCortexBinaryPGLSOut/cortex_groupLiving_results.csv -p RM-shared -q phyloglm -s 0 -t 2:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortex.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortex.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexBinaryPGLSOut/cortex_groupLiving_results_r1_s-1663264308.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m MoMaRaBaEnhancersNRSummit_WBS.txt -n 18 -o GroupLivingMotorCortexBinaryPGLSOut/cortex_groupLiving_results_round1.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortex1.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results_perm1k.csv
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results_perm1k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_peaks_perm1k_p005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_peaks_perm1k_p005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_WBS.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_preds_perm1k_p005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m cortex_groupLiving_preds_perm1k_p005.txt -n 2 -o GroupLivingMotorCortexBinaryPGLSOut/cortex_groupLiving_results_round2.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortex2.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortex2.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results_perm10k.csv
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results_perm10k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_peaks_perm10k_p0005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_peaks_perm10k_p0005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_WBS.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_preds_perm10k_p0005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m cortex_groupLiving_preds_perm10k_p0005.txt -n 1 -o GroupLivingMotorCortexBinaryPGLSOut/cortex_groupLiving_results_round3.csv -p RM-shared -q phyloglm -s 90000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortex3.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results_perm100k.csv
awk -F , '$4 < 0.0005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_results_perm100k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_groupLiving_peaks_perm100k_p00005.txt # No peaks

# Group living, motor cortex, genome-wide
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m MoMaRaBaEnhancersNRSummit.txt -n 1 -o GroupLivingMotorCortexFullBinaryPGLSOut/cortex_full_groupLiving_results.csv -p RM-shared -q phyloglm -s 0 -t 2:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/cortex_full_groupLiving_results_r1_s1504928811.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results.csv 
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m MoMaRaBaEnhancersNRSummit.txt -n 1000 -o GroupLivingMotorCortexFullBinaryPGLSOut/cortex_full_groupLiving_results_round1.csv -p RM-shared -q phyloglm -s 999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull1.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull1.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm1k.csv
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm1k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_peaks_perm1k_p005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_peaks_perm1k_p005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_preds_perm1k_p005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m cortex_full_groupLiving_preds_perm1k_p005.txt -n 1000 -o GroupLivingMotorCortexFullBinaryPGLSOut/cortex_full_groupLiving_results_round2.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull2.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull2.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm10k.csv
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm10k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_peaks_perm10k_p0005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_peaks_perm10k_p0005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_preds_perm10k_p0005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m cortex_full_groupLiving_preds_perm10k_p0005.txt -n 804 -o GroupLivingMotorCortexFullBinaryPGLSOut/cortex_full_groupLiving_results_round3.csv -p RM-shared -q phyloglm -s 90000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull3.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull3.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm100k.csv
awk -F , '$4 < 0.0005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm100k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_peaks_perm100k_p00005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_peaks_perm100k_p00005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_preds_perm100k_p00005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m cortex_full_groupLiving_preds_perm100k_p00005.txt -n 81 -o GroupLivingMotorCortexFullBinaryPGLSOut/cortex_full_groupLiving_results_round4.csv -p RM-shared -q phyloglm -s 900000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull4.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm1m.csv
python /jet/home/ikaplow/OCROrthologPrediction/src/filterPeakName.py --unfilteredPeakFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit.txt --unfilteredPeakNameCol 0 --peakListFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_preds_perm1k_p005.txt --removePeaks --outputFileName /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoMaRaBaEnhancersNRSummit_groupLivingRound2NotUsed.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingM1 -m MoMaRaBaEnhancersNRSummit_groupLivingRound2NotUsed.txt -n 1000 -o GroupLivingMotorCortexFullBinaryPGLSOut/cortex_full_groupLiving_results_round2a.csv -p RM-shared -q phyloglm -s 9000 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull2a.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingMotorCortexFull2a.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/*round3* /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOutPlus
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/*round4* /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOutPlus
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingMotorCortexFullBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/cortex_full_groupLiving_results_perm10kAll.csv

# Group living, liver
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLiving -m MoRaMaCoPiEnhancersNRSummit_WBS.txt -n 1 -o GroupLivingLiverBinaryPGLSOut/liver_groupLiving_results.csv -p RM-shared -q phyloglm -s 0 -t 1:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingLiver.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingLiver.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingLiverBinaryPGLSOut/liver_groupLiving_results_r1_s-10000537.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLiving -m MoRaMaCoPiEnhancersNRSummit_WBS.txt -n 21 -o GroupLivingLiverBinaryPGLSOut/liver_groupLiving_results_round1.csv -p RM-shared -q phyloglm -s 999 -t 1:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingLiver1.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingLiver1.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingLiverBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_results_perm1k.csv
awk -F , '$4 < 0.05 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_results_perm1k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_peaks_perm1k_p005.txt
grep -f /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_peaks_perm1k_p005.txt /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/MoRaMaCoPiEnhancersNRSummit_WBS.txt > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_preds_perm1k_p005.txt
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c BoreoeutheriaSpeciesNamesNew.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLiving -m liver_groupLiving_preds_perm1k_p005.txt -n 4 -o GroupLivingLiverBinaryPGLSOut/liver_groupLiving_results_round2.csv -p RM-shared -q phyloglm -s 90000 -t 10:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1000 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingLiver2.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingLiverBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_results_perm10k.csv
awk -F , '$4 < 0.005 { print }' /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_results_perm10k.csv | cut -d , -f 1 | tail -n +2 > /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/liver_groupLiving_peaks_perm10k_p0005.txt # No peaks

# Group living, PV, genome-wide, excluding 1st iteration
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c PVSpeciesOrder.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLiving -m PV_MoHu_AvgActivityPredictions_boreoeutheria_222species_olapFilt_modified.txt -n 1 -o GroupLivingPvBinaryPGLSOut/Pv_groupLiving_results.csv -p RM-shared -q phyloglm -s 0 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingPv.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingPv.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingPvBinaryPGLSOut/Pv_groupLiving_results_r1_s-1749755317.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/Pv_groupLiving_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a SocialPhenotypes.csv -b group_living_euarchontoglires -c PVSpeciesOrder.txt -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j GroupLivingPv -m PV_MoHu_AvgActivityPredictions_boreoeutheria_222species_olapFilt_modified.txt -n 1000 -o GroupLivingPvBinaryPGLSOut/Pv_groupLiving_results_rounds1And2.csv -p RM-shared -q phyloglm -s 9999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1500 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingPv1And2.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runBinaryPGLSGroupLivingPv1And2.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/Pv_groupLiving_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/GroupLivingPvBinaryPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/Pv_groupLiving_results_perm10k.csv

# Turbinals, olfactory receptors
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Phenotypes_OR_modified.csv -b Turbinals -c ZoonomiaSpeciesNamesOR.txt  -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j ORTurbinal -m ORCounts.txt -n 1 -o ORPGLSOut/OR_Turbinal_results.csv -p RM-shared -q phylolm -s 0 -t 1:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1999 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runPGLSTurbinalOR.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runPGLSTurbinalOR.bash
mv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/ORPGLSOut/OR_Turbinal_results_r1_s2063983108.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/OR_Turbinal_results.csv
python /jet/home/ikaplow/PGLSScripts/makePGLSSbatch.py -a Phenotypes_OR_modified.csv -b Turbinals -c ZoonomiaSpeciesNamesOR.txt  -d /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes -j ORTurbinal -m ORCounts.txt -n 1 -o ORPGLSOut/OR_Turbinal_results.csv -p RM-shared -q phylolm -s 999999 -t 48:00:00 -y Zoonomia_ChrX_lessGC40_241species_30Consensus.tree -l /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/LogFiles -r 1999 -e /jet/home/ikaplow/PGLSScripts > /jet/home/ikaplow/RegElEvoCode/runPGLSTurbinalORAllPerm.bash
sbatch /jet/home/ikaplow/RegElEvoCode/runPGLSTurbinalORAllPerm.bash
/jet/home/ikaplow/PGLSScripts/compute_exper_pvals.py /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/OR_Turbinal_results.csv /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/ORPGLSOut/ /ocean/projects/bio200034p/ikaplow/PredictionsToPhenotypes/OR_Turbinal_results_perm1m.csv
