# Prepare brain size enhancers (prepareDataForPrank.py requires python3 and >=32GB)
# Mouse
cut -f 1 -d , /home/dschaffe/enhancer-clustering/data/cortex/regression/brain_size/processed/cortex_brain-size_results_perm1m.csv | grep mo | sed 's/\_mo//g' > /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsMouseWithReps.txt
python /home/ikaplow/RegulatoryElementEvolutionProject/src/OCROrthologPrediction/src/filterPeakName.py --unfilteredPeakFileName /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsMouseWithReps.txt --unfilteredPeakNameCol 0 --peakListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/Cortex_All_ATAC_out/peak/macs2/idr/optimal_set/Pfenning_bulk_Ctx_nonCDS_enhancerShort_unique.bed --peakNameCol 3 --outputFileName /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsMouse.txt
sort -k2,2n /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeIndex.txt | cut -f1 > /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt
paste /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheria.txt /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeIndex.txt | sort -k3,3n | cut -f1 > /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrder.txt
paste /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheria.txt /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeIndex.txt | sort -k3,3n | cut -f1 > /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrder.txt
paste /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/Cortex_All_ATAC_out/peak/macs2/idr/optimal_set/LiftedPeaks/liftedPeakAllFileNamesConvertedBoreoeutheria.txt /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeIndex.txt | sort -k3,3n | cut -f1 > /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/Cortex_All_ATAC_out/peak/macs2/idr/optimal_set/LiftedPeaks/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/Cortex_All_ATAC_out/peak/macs2/idr/optimal_set/LiftedPeaks/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 15 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsMouse.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrder.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrder.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/BrainSizeForPRANK --individualPeakFileNameSuffix mouseOrthologs.fa --outputFileNameSuffix mousePrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeMouse.sh
# Rat
cut -f 1 -d , /home/dschaffe/enhancer-clustering/data/cortex/regression/brain_size/processed/cortex_brain-size_results_perm1m.csv | grep ra | sed 's/\_ra//g' > /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsRat.txt
paste /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/RatAtac/M1_AllReps/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheria.txt /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeIndex.txt | sort -k3,3n | cut -f1 > /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/RatAtac/M1_AllReps/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/RatAtac/M1_AllReps/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 12 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsRat.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrder.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrder.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/BrainSizeForPRANK --individualPeakFileNameSuffix ratOrthologs.fa --outputFileNameSuffix ratPrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeRat.sh
# Macaque
cut -f 1 -d , /home/dschaffe/enhancer-clustering/data/cortex/regression/brain_size/processed/cortex_brain-size_results_perm1m.csv | grep ma | sed 's/\_ma//g' > /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsMacaque.txt
paste /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheria.txt /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeIndex.txt | sort -k3,3n | cut -f1 > /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 83 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsMacaque.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrder.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrder.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/BrainSizeForPRANK --individualPeakFileNameSuffix macaqueOrthologs.fa --outputFileNameSuffix macaquePrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeMacaque.sh
# Bat
cut -f 1 -d , /home/dschaffe/enhancer-clustering/data/cortex/regression/brain_size/processed/cortex_brain-size_results_perm1m.csv | grep ba | sed 's/\_ba//g' > /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsBat.txt
paste /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/BatAtac/OfMBat1K/call-reproducibility_idr/execution/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheria.txt /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeIndex.txt | sort -k3,3n | cut -f1 > /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/BatAtac/OfMBat1K/call-reproducibility_idr/execution/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/BatAtac/OfMBat1K/call-reproducibility_idr/execution/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 111 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/brainSizeOCRsBat.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrderModified.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrderModified.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/BrainSizeForPRANK --individualPeakFileNameSuffix batOrthologs.fa --outputFileNameSuffix batPrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeBat.sh
# Combine
cat /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeMouse.sh /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeMacaque.sh /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeRat.sh /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeBat.sh | sed 's/\-showxml\ \-showanc/\-DNA\ \-once\ \-f\=paml \-prunetree/g' > /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKBrainSizeScript.sh

# Prepare vocal learning enhancers (prepareDataForPrank.py requires python3 and >=32GB)
# Mouse
cut -f 1 -d , /projects/MPRA/Irene/PGLSOutputs/cortex_VocalLearner_results_perm1m_atLeast3True_orthologInChiropteraVocalLearner_orthologInNonChiropteraVocalLearner_noRep.csv | grep mo | sed 's/\_mo//g' > /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsMouse.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/Cortex_All_ATAC_out/peak/macs2/idr/optimal_set/LiftedPeaks/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 15 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsMouse.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrder.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrder.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/VocalLearningForPRANK --individualPeakFileNameSuffix mouseOrthologs.fa --outputFileNameSuffix mousePrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningMouse.sh
# Rat
cut -f 1 -d , /projects/MPRA/Irene/PGLSOutputs/cortex_VocalLearner_results_perm1m_atLeast3True_orthologInChiropteraVocalLearner_orthologInNonChiropteraVocalLearner_noRep.csv | grep ra | sed 's/\_ra//g' > /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsRat.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/RatAtac/M1_AllReps/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 12 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsRat.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrder.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrder.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/VocalLearningForPRANK --individualPeakFileNameSuffix ratOrthologs.fa --outputFileNameSuffix ratPrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningRat.sh
# Macaque
cut -f 1 -d , /projects/MPRA/Irene/PGLSOutputs/cortex_VocalLearner_results_perm1m_atLeast3True_orthologInChiropteraVocalLearner_orthologInNonChiropteraVocalLearner_noRep.csv | grep ma | sed 's/\_ma//g' > /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsMacaque.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MacaqueAtac/OfM/peak/idr_reproducibility/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 83 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsMacaque.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrder.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrder.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/VocalLearningForPRANK --individualPeakFileNameSuffix macaqueOrthologs.fa --outputFileNameSuffix macaquePrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningMacaque.sh
# Bat
cut -f 1 -d , /projects/MPRA/Irene/PGLSOutputs/cortex_VocalLearner_results_perm1m_atLeast3True_orthologInChiropteraVocalLearner_orthologInNonChiropteraVocalLearner_noRep.csv | grep ba | sed 's/\_ba//g' > /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsBat.txt
/home/ikaplow/miniconda3/bin/python3 /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/prepareDataForPrank.py --bedFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/BatAtac/OfMBat1K/call-reproducibility_idr/execution/LiftedPeaksFixed/liftedPeakAllFileNamesConvertedBoreoeutheriaTreeOrder.txt --baseSpeciesLine 111 --peaksToIncludeFileName /projects/MPRA/Irene/PGLSOutputs/vocalLearningOCRsBat.txt --fastaFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/200MammalsAssembliesFileNamesBoreoeutheriaTreeOrderModified.txt --chromSizesFileNameListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/chromSizesFileNamesBoreoeutheriaTreeOrderModified.txt --extendedSummits --sequenceLength 500 --speciesListFileName /projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/200MammalsAdditionalFastas/BoreoeutheriaSpeciesNamesNewContTreeOrder.txt --speciesTreeFileName /home/dschaffe/enhancer-clustering/data/Zoonomia_ChrX_lessGC40_241species_30Consensus.tree --prankDataDir /projects/MPRA/Irene/PGLSOutputs/VocalLearningForPRANK --individualPeakFileNameSuffix batOrthologs.fa --outputFileNameSuffix batPrankOutputs.fas --scriptFileName /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningBat.sh
# Combine
cat /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningMouse.sh /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningRat.sh /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningMacaque.sh /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningBat.sh | sed 's/\-showxml\ \-showanc/\-DNA\ \-once\ \-f\=paml \-prunetree/g' > /home/ikaplow/RegulatoryElementEvolutionProject/src/RegElEvoCode/runPRANKVocalLearningScript.sh
